global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'football-tickets'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.containers.internal:8080']
